trufnetwork/sdk-js

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/semantic-pr.yml

resolves: https://github.com/truflation/tsn-sdk-js/issues/3

docs: add github template

---

package.json
src/types/client.ts
src/types/contractValues.ts
src/types/stream.ts
src/util/EthereumAddress.ts
src/util/StreamId.ts
src/util/types.ts
src/util/visibility.ts
tsconfig.json
vitest.config.ts

- fix https://github.com/truflation/tsn/issues/684

feat: implement utilities

---

README.md
docs/api-reference.md
docs/core-concepts.md
docs/getting-started.md

- fix https://github.com/truflation/tsn/issues/693
untested docs

chore: initial docs

---

src/contracts-api/stream.ts
tests/integration/primitiveStream.test.ts

- Adding the ability to use custom named procedure with get record input and output as its signature
resolves: https://github.com/trufnetwork/sdk-js/issues/25
Tested with test

feat: use custom procedure

---

README.md
examples/index.ts
examples/package-lock.json
examples/package.json

This pull request introduces several changes to the `README.md` file and adds a new example directory with helper functions and a sample script. Additionally, it includes updates to the package configuration files to support the new examples.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30-R33): Added an example for creating a wallet using the `ethers` library and updated the `chainId` to "truflation-staging-2024-11-22". Also, introduced a new link to the TN SDK JS Example Directory. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30-R33) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L38-R42) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac0 …

docs: Comprehensive SDK-JS Example

---

README.md
docs/api-reference.md
docs/getting-started.md
examples/index.ts
package.json
src/client/client.ts
src/contracts-api/action.ts
src/contracts-api/composedAction.ts
src/contracts-api/deleteStream.ts
src/contracts-api/primitiveAction.ts
src/index.common.ts
tests/integration/composedStream.test.ts
tests/integration/getListStreams.test.ts
tests/integration/permissions.test.ts
tests/integration/primitiveStream.test.ts

This pull request primarily focuses on renaming and refactoring the terminology and methods related to streams to actions across various files. Additionally, it includes updates to the documentation and some minor code improvements.
* [`src/client/client.ts`](diffhunk://#diff-ed2b939cef6b7455068ab86c443272afeb42f47a0264b82ec98fbd19d774e4d1L153-R154): Renamed methods from `loadStream`, `loadPrimitiveStream`, and `loadComposedStream` to `loadAction`, `loadPrimitiveAction`, and `loadComposedAction` respectively. [[1]](diffhunk://#diff-ed2b939cef6b7455068ab86c443272afeb42f47a0264b82ec98fbd19d774e4d1L153-R154) [[2]](diffhunk://#diff-ed2b939cef6b7455068ab86c443272afeb42f47a0264b82ec98fbd19d774e4d1L164-R173)
* [`src/contracts-api/stream.ts`](diffhunk://#diff-22e769089e3cc3a88c485d1aed19c7316daa70 …

feat: configure authorization of a stream v2

---

README.md

> Updated documentation to include Shimming instructions for serverless users, specifically around challenges I had with using NextJS
Resolves: https://github.com/trufnetwork/sdk-js/issues/43
Documented fix has been tested in a different project

docs: document nextjs shimming

---

README.md
examples/index.ts
src/client/client.ts
src/contracts-api/composedStream.ts
src/contracts-api/deployStream.ts

resolves: https://github.com/trufnetwork/sdk-js/issues/62

feat: view Stream Composition after being set on on explorer

---

README.md

Observasionly, there is formatting error on README.

docs: view README's example section in correct formatting

---

package.json
src/client/getLastTransactions.ts
src/types/transaction.ts

resolves: https://github.com/trufnetwork/sdk-js/issues/73
```
tsx index.ts 
Last transactions: [
{
blockHeight: 322,
method: 'insertRecords',
sender: '4710a8d8f0d845da110086812a32de6d90d7ff5c',
transactionHash: '5e363ba8253e36fe4a7ea645dde341332d88e3acf47d0eb1e214a694a2a0f66a',
stampMs: 1746493080687
},
{
blockHeight: 321,
method: 'insertRecords',
sender: '4710a8d8f0d845da110086812a32de6d90d7ff5c',
transactionHash: 'edfe4c017ca9de4103384d975e2715507e04e19acc1a369482d8ff74edb1d8a0',
stampMs: 1746492873453
},
{
blockHeight: 320,
method: 'insertRecords',
sender: '4710a8d8f0d845da110086812a32de6d90d7ff5c',
transactionHash: '575a927c5f6b1f8b1eea2a77914a4cd6793c092add38701eb893f9d60873a19f',
stampMs: 1746492654693
},
{
blockHeight: 319,
method: 'insertRecords',
sender: …
```

feat: view transaction age

---

docs/api-reference.md
docs/getting-started.md
examples/index.ts

resolves: https://github.com/trufnetwork/truf-network/issues/706

docs: update api-references to reflect  new architecture changes

---

README.md
docs/api-reference.md
docs/core-concepts.md
docs/getting-started.md

resolves: https://github.com/trufnetwork/node/issues/934

docs: v2 documentation structure and core concepts

---

src/client/client.ts
src/client/listStreams.ts
tests/integration/getListStreams.test.ts

resolves: https://github.com/trufnetwork/truf-network/issues/828

chore: block height filter on list streams

---

README.md
docs/api-reference.md
docs/core-concepts.md
docs/getting-started.md
examples/complex_example/README.md
examples/complex_example/index.ts
examples/complex_example/package.json

- Comprehensively update core concepts documentation
- Improve API reference with detailed method descriptions
- Add in-depth explanations of stream lifecycle
- Provide more context for stream management and composition
- Clarify error handling and performance considerations
resolves: https://github.com/trufnetwork/truf-network/issues/850
resolves: https://github.com/trufnetwork/truf-network/issues/845

docs: view complex example with stream creation and enhance docs

---

docs/local-node-guide.md

resolves https://github.com/trufnetwork/docs/issues/115

fix(docs): view read stream with local node guide

---

README.md
src/client/client.ts
src/contracts-api/composedAction.ts
src/contracts-api/deployStream.ts

resolves: https://github.com/trufnetwork/truf-network/issues/846

chore: remove v1 synchronizer

---

package.json
tests/integration/composedStream.test.ts
tests/integration/databaseSize.test.ts
tests/integration/getListStreams.test.ts
tests/integration/permissions.test.ts
tests/integration/primitiveStream.test.ts
tests/integration/roleManagement.test.ts
tests/integration/trufnetwork.setup.ts
tests/integration/utils.ts
vitest.config.ts

- setup to auto initiate node for tests
- modify old tests to pass with role management
- add new tests about role managemnet
- fix #88 
all pass

chore: test role management & node fixture

---

docs/api-reference.md
examples/custom_procedure_example/README.md
examples/custom_procedure_example/index.ts
examples/custom_procedure_example/package.json

resolves: https://github.com/trufnetwork/truf-data-provider/issues/709
run using pnpm start on the example custom procedure directory
```
~/trufnetwork/sdk-js/examples/custom_procedure_example$ pnpm start
> custom_procedure_example@1.0.0 start /home/micbun/trufnetwork/sdk-js/examples/custom_procedure_example
> tsx index.ts
Custom procedure result: [
{ eventTime: '1749600000', value: '-0.153778736787248705' },
{ eventTime: '1749686400', value: '-0.188389531724398578' },
{ eventTime: '1749772800', value: '-0.202850280496099510' },
{ eventTime: '1749859200', value: '-0.158426061594466221' },
{ eventTime: '1749945600', value: '-0.193030199739482099' },
{ eventTime: '1750032000', value: '-0.194126223178857021' }
]
```

chore: view custom action example

---

docs/api-reference.md

resolves: https://github.com/trufnetwork/truf-network/issues/862

docs: view detailed explanation about stream methods

---

README.md
docs/api-reference.md
docs/core-concepts.md
docs/getting-started.md
examples/complex_example/index.ts

resolves https://github.com/trufnetwork/truf-network/issues/915

docs(ui): view sdk examples using UNIX seconds

---

examples/README.md
examples/complex_example/README.md
examples/complex_example/package.json
examples/custom_procedure_example/README.md
examples/custom_procedure_example/package.json
examples/custom_procedure_with_prefix_example/README.md
examples/custom_procedure_with_prefix_example/index.ts
examples/custom_procedure_with_prefix_example/package.json
examples/package.json
src/contracts-api/action.ts

resolves: https://github.com/trufnetwork/node/issues/1013

chore: add prefix on get record and index

---

src/contracts-api/composedAction.ts

The import is unused, was reintroduced on a merge, but removing it is safe
- fix #104

chore: remove unused pg import from composedAction

---

README.md
docs/api-reference.md

resolves: https://github.com/trufnetwork/truf-network/issues/1126

docs: improve taxonomy method visibility and quick references

---

src/contracts-api/action.ts

resolves: https://github.com/trufnetwork/truf-network/issues/1203

chore: rename bridge action

---

src/client/client.ts
src/contracts-api/action.ts
tests/integration/erc20Bridge.test.ts

resolvse: https://github.com/trufnetwork/truf-network/issues/1201

feat: view wallet rewards
